name: Build & Push Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_BASE: ghcr.io/gdragos79/myprojectappprod
    steps:
      - uses: actions/checkout@v4

      - name: Derive short SHA
        id: meta
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build+Push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./frontend.Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}-frontend:${{ steps.meta.outputs.sha_short }}
            ${{ env.IMAGE_BASE }}-frontend:latest

      - name: Build+Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend.Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}-backend:${{ steps.meta.outputs.sha_short }}
            ${{ env.IMAGE_BASE }}-backend:latest
