name: CI (Build & Test)

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect backend path
        id: detect_backend
        shell: bash
        run: |
          set -euo pipefail
          if [ -f "apps/backend/package.json" ]; then
            echo "dir=apps/backend" >> "$GITHUB_OUTPUT"
          elif [ -f "backend/package.json" ]; then
            echo "dir=backend" >> "$GITHUB_OUTPUT"
          else
            echo "dir=" >> "$GITHUB_OUTPUT"
          fi

      - name: Backend deps (prefer lockfile; fallback to install)
        if: steps.detect_backend.outputs.dir != ''
        working-directory: ${{ steps.detect_backend.outputs.dir }}
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "No package-lock.json → using npm install"
            npm install --no-audit --no-fund
          fi

      - name: Backend tests (skip if no test script)
        if: steps.detect_backend.outputs.dir != ''
        working-directory: ${{ steps.detect_backend.outputs.dir }}
        run: npm run test --if-present -- --runInBand || echo "No backend tests yet"

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect frontend path
        id: detect_frontend
        shell: bash
        run: |
          set -euo pipefail
          if [ -f "apps/frontend/package.json" ]; then
            echo "dir=apps/frontend" >> "$GITHUB_OUTPUT"
          elif [ -f "react/package.json" ]; then
            echo "dir=react" >> "$GITHUB_OUTPUT"
          else
            echo "dir=" >> "$GITHUB_OUTPUT"
          fi

      - name: Frontend deps
        if: steps.detect_frontend.outputs.dir != ''
        working-directory: ${{ steps.detect_frontend.outputs.dir }}
        run: npm ci

      - name: Frontend build (skip if no script)
        if: steps.detect_frontend.outputs.dir != ''
        working-directory: ${{ steps.detect_frontend.outputs.dir }}
        run: npm run build --if-present || echo "No frontend build script"
