name: CI (Build & Test)

on:
  pull_request:
    branches: [ main, staging, development ]
  push:
    branches: ['**']   # run on pushes to any branch
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm test --if-present
      - run: npm run build --if-present

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: react/package-lock.json
      - run: npm ci
      - run: npm test --if-present
      - run: npm run build --if-present

  images:
    name: Docker Build (validate; push only on non-PR)
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_BACKEND:  ghcr.io/gdragos79/myprojectappprod-backend
      IMAGE_FRONTEND: ghcr.io/gdragos79/myprojectappprod-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Debug tree & verify Dockerfiles
        run: |
          echo "HEAD=$(git rev-parse --short HEAD)"
          ls -la
          ls -la backend || true
          ls -la react   || true
          test -f backend/Dockerfile || (echo "::error:: missing backend/Dockerfile"; exit 1)
          test -f react/Dockerfile   || (echo "::error:: missing react/Dockerfile"; exit 1)

      - name: Login to GHCR (skip on PR)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: Dockerfile            # relative to the 'backend' context
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_BACKEND }}:ci-${{ github.run_id }}

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: react
          file: Dockerfile            # relative to the 'react' context
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_FRONTEND }}:ci-${{ github.run_id }}
