name: Deploy (Development)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy (sha7 or 'latest')"
        required: true
        default: "latest"
      color:
        description: "Which color to deploy to?"
        required: true
        default: "blue"
        type: choice
        options: ["blue", "green"]
      switch_traffic:
        description: "Switch the proxy to the chosen color after deployment?"
        required: true
        default: "false"
        type: choice
        options: ["true", "false"]

permissions:
  contents: read

jobs:
  deploy:
    # GitHub-hosted runner is fine because Tailscale gives it secure reachability
    runs-on: ubuntu-latest
    environment: Development
    concurrency:
      group: deploy-development
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      # --- Join your tailnet with an ephemeral key stored as secret TS_AUTHKEY ---
      # Prereq (Option A):
      #   * Tailscale installed & logged-in on BLUE/GREEN/PROXY VMs
      #   * APP_*_SSH_HOST secrets point to their MagicDNS names (or 100.x IPs)
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
          args: --timeout=2m --accept-routes

      # --- If your GHCR images are PRIVATE, uncomment the next step and
      #     add GHCR_USERNAME & GHCR_TOKEN (read:packages) to the Development env.
      # - name: Login to GHCR (runner; sometimes useful for preflight pulls)
      #   run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # -------------------- Deploy to BLUE --------------------
      - name: Deploy to BLUE
        if: ${{ inputs.color == 'blue' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.APP_BLUE_SSH_HOST }}   # MagicDNS or 100.x of BLUE
          username: ${{ secrets.APP_BLUE_SSH_USER }}   # e.g., deploy
          key:      ${{ secrets.APP_BLUE_SSH_KEY }}    # full private key (multiline OK)
          script_stop: true
          script: |
            set -e
            STACK=myapp_blue
            mkdir -p ~/app/$STACK
            cd ~/app/$STACK

            # If GHCR packages are PRIVATE, uncomment the next line and add GHCR secrets:
            # echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

            # Compose env (variables used in docker-compose.yml)
            cat > .env <<'EOF'
            TAG=${{ inputs.tag }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            EOF

            # Production runtime compose (frontend serves static; proxies /api -> backend)
            cat > docker-compose.yml <<'YAML'
            services:
              frontend:
                image: ghcr.io/${{ github.repository }}-frontend:${TAG:-latest}
                ports:
                  - "80:80"
                depends_on: [backend]

              backend:
                image: ghcr.io/${{ github.repository }}-backend:${TAG:-latest}
                environment:
                  DB_HOST: ${DB_HOST}
                  DB_PORT: ${DB_PORT}
                  DB_USER: ${DB_USER}
                  DB_PASSWORD: ${DB_PASSWORD}
                  DB_NAME: ${DB_NAME}
                ports:
                  - "3000:3000"
                healthcheck:
                  test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/health').then(r=>{if(r.ok)process.exit(0);else process.exit(1)}).catch(()=>process.exit(1))"]
                  interval: 15s
                  timeout: 5s
                  retries: 5
            YAML

            docker compose --env-file .env pull
            docker compose --env-file .env up -d --remove-orphans
            sleep 3
            curl -fsS http://localhost/api/health || (docker compose logs --no-color --tail=200; exit 1)

      # -------------------- Deploy to GREEN --------------------
      - name: Deploy to GREEN
        if: ${{ inputs.color == 'green' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.APP_GREEN_SSH_HOST }}  # MagicDNS or 100.x of GREEN
          username: ${{ secrets.APP_GREEN_SSH_USER }}
          key:      ${{ secrets.APP_GREEN_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            STACK=myapp_green
            mkdir -p ~/app/$STACK
            cd ~/app/$STACK

            # If GHCR packages are PRIVATE, uncomment the next line and add GHCR secrets:
            # echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

            cat > .env <<'EOF'
            TAG=${{ inputs.tag }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            EOF

            cat > docker-compose.yml <<'YAML'
            services:
              frontend:
                image: ghcr.io/${{ github.repository }}-frontend:${TAG:-latest}
                ports:
                  - "80:80"
                depends_on: [backend]

              backend:
                image: ghcr.io/${{ github.repository }}-backend:${TAG:-latest}
                environment:
                  DB_HOST: ${DB_HOST}
                  DB_PORT: ${DB_PORT}
                  DB_USER: ${DB_USER}
                  DB_PASSWORD: ${DB_PASSWORD}
                  DB_NAME: ${DB_NAME}
                ports:
                  - "3000:3000"
                healthcheck:
                  test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/health').then(r=>{if(r.ok)process.exit(0);else process.exit(1)}).catch(()=>process.exit(1))"]
                  interval: 15s
                  timeout: 5s
                  retries: 5
            YAML

            docker compose --env-file .env pull
            docker compose --env-file .env up -d --remove-orphans
            sleep 3
            curl -fsS http://localhost/api/health || (docker compose logs --no-color --tail=200; exit 1)

      # -------------------- Switch traffic on Proxy VM --------------------
      - name: Switch proxy to selected color
        if: ${{ inputs.switch_traffic == 'true' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.PROXY_SSH_HOST }}       # MagicDNS or 100.x of PROXY
          username: ${{ secrets.PROXY_SSH_USER }}
          key:      ${{ secrets.PROXY_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            COLOR=${{ inputs.color }}
            sudo ln -sfn /etc/nginx/upstreams/$COLOR.conf /etc/nginx/upstreams/active.conf
            sudo nginx -t
            sudo systemctl reload nginx
            # Optional smoke test through proxy box itself
            curl -fsS http://localhost/api/health || (echo "Proxy smoke test failed" && exit 1)
