name: Publish images to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # IMPORTANT: do NOT set "path:" here. Leave it at workspace root.

      - name: Show layout (debug)
        run: |
          echo "PWD=$PWD"
          ls -la
          echo "---- backend ----"
          ls -la backend || true
          echo "---- frontend ----"
          ls -la frontend || true

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Backend
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/backend
          file: ${{ github.workspace }}/backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/myprojectapp-backend:latest
            ghcr.io/${{ github.repository_owner }}/myprojectapp-backend:sha-${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true

      # Frontend
      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/frontend
          file: ${{ github.workspace }}/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/myprojectapp-frontend:latest
            ghcr.io/${{ github.repository_owner }}/myprojectapp-frontend:sha-${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
